const CardProduct = [
    {
      id: 1,
      name: "X1",
      type: "X-factor",
      src: 'src/assets/img/X-factor/X1.png',
      discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
      price: "25,999",
      old :"30,000" ,
      qty: 1,
    },
    {
        id: 2,
        name: "X2",
        type: "X-factor",
        src: 'src/assets/img/X-factor/X2.png',
        discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
        price: "28,985 ",
        old :"30,000" ,
        qty: 1,
    },
    {
        id: 3,
        name: "X3",
        type: "X-factor",
        src: 'src/assets/img/X-factor/X3.png',
        discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
        price: "28,566",
        old :"30,000" ,
        qty: 1,
    },
    {
        id: 4,
        name: "Doodle v2",
        type: "Desire",
        src: 'src/assets/img/Desire/Doodle v2.png',
        discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
        price: " 28,566",
        old :"30,000" ,
        qty: 1,
    },{
        id: 5,
        name: "EMX Aqua",
        type: "Desire",
        src: 'src/assets/img/Desire/EMX Aqua.png',
        discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
        price: " 28,566",
        old :"30,000" ,
        qty: 1,
    },
    {
        id: 6,
        name: "EMX",
        type: "Desire",
        src: 'src/assets/img/Desire/EMX.png',
        discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
        price: " 28,566",
        old :"30,000" ,
        qty: 1,
    },
    {
        id: 7,
        name: "EMX+",
        type: "Desire",
        src: 'src/assets/img/Desire/EMX+.png',
        discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
        price: "28,566 ",
        old :"30,000" ,
        qty: 1,
    },
    {
        id: 8,
        name: "Lil E",
        type: "Desire",
        src: 'src/assets/img/Desire/Lil E.png',
        discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
        price: "28,566 ",
        old :"30,000" ,
        qty: 1,
    },
    {
        id: 9,
        name: "T-REX+",
        type: "Desire",
        src: 'src/assets/img/Desire/T-Rex+.png',
        discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
        price: "28,566 ",
        old :"30,000" ,
        qty: 1,
    },
    {
        id: 10,
        name: "Desert Eagle",
        type: "Elite",
        src: 'src/assets/img/Elite/Desert Eagle.png',
        discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
        price: "28,566 ",
        old :"30,000" ,
        qty: 1,
    },
    {
        id: 11,
        name: "Nighthawk",
        type: "Elite",
        src: 'src/assets/img/Elite/Nighthawk.png',
        discription: "Traverse through town and trails without fuss or effort! India's first dual suspension e-cycle, EMX+, offers a comfy ride and the power to cruise. Designed to flash past city traffic, beat uneven roads into submission, and tear through the steepest of slopes - it's always got your back!",
        price: " 28,566",
        old :"30,000" ,
        qty: 1,
    },
];


export default CardProduct